### ISSUE TITLE
Disable fullscreen

### ISSUE THREAD

**Issue by erikdung** [bradoyler/newswatch-react-native#1]
Hi,
is there a way to set youtube parameter playinline to disable fullscreen on default? Thanks

**Comment by bradoyler** [comment]
I'm not clear on what kind of user experience you're looking for.

**Comment by erikdung** [comment]
I would like to play video inline, not fullscreen, so user could do something else when video is playing. I plan to stream video via Apple TV, then user could see video on TV and search for videos on iPhone.

**Comment by bradoyler** [comment]
A "docked" video player wouldn't be a simple change. 
Right now, video is loaded via the YouTube embed link in a Webview.
see: https://github.com/bradoyler/newswatch-react-native/blob/master/VideoWebView.js#L17

**Comment by bradoyler** [comment]
@erikdung feel free to fork this repo if that helps
