### ISSUE TITLE
Missing fetch 

### ISSUE THREAD

**Issue by hbizira** [bradoyler/newswatch-react-native#2]
When I follow the instructions in the readme, this error happens upon first run:

https://www.dropbox.com/s/dbzdhbyluyllr8k/Screenshot%202015-05-14%2015.30.57.png?dl=0&raw=1

I tried adding fetch library to the package.json but the error remains. Not sure how to fix it.

**Comment by bradoyler** [comment]
@hbizira Thx. Just noticed this after upgrading to [RN v0.4.3](https://github.com/facebook/react-native/releases/tag/v0.4.3)
I'll provide a hotfix soon...

**Comment by bradoyler** [comment]
@hbizira easy fix. Give it another pull. Cheers.

**Comment by hbizira** [comment]
Thanks!!
