### ISSUE TITLE
a year later.. how about another upgrade.. to rn 0.40 :)

### ISSUE THREAD

**Issue by vesper8** [bradoyler/newswatch-react-native#5]
and make it work on exponent for bonus appreciation!!! i would love you!!

**Comment by bradoyler** [comment]
upgraded to 0.49 using [create-react-native-app](https://github.com/react-community/create-react-native-app)

**Comment by vesper8** [comment]
that's fantastic!! thanks for taking the time!

did you do a git rebase or something? I only see the new version now and the old is gone.. that's ok but it might have been nice to actually see what you upgraded :)

will check out the new version, thanks again!

**Comment by bradoyler** [comment]
I basically had to re-implement everything. A LOT changed with react over the past 2 yrs. 
Gonna continue to bring all the features back soon.

**Comment by vesper8** [comment]
awesome!! love what you're doing!
